variables:
  coverage_path: "./coverage.xml"
  APPLICATION_NAME: orbis2

  DOCKER_IMAGE: registry.gitlab.semanticlab.net/fhgr/future-of-work/$CI_PROJECT_NAME
  KUBE_NAMESPACE_FHGR: fow-production
  HELM_CHART_NAME_FHGR: chart
  URL_FHGR: prod.semanticlab.net
  VERSION: "1.0"

stages:
    - Pre Static Analysis
    - Test
    - Post Static Analysis
    - Docker Build
    - Kubernetes Deployment

pep8:
  image: "python:3.8"
  stage: Pre Static Analysis
  script:
    - pip install tox
    - pip install tox-pip-version
    - tox -e pep8
  tags:
    - docker
  allow_failure: true


pytest:
  image: "python:3.8"
  stage: Test
  services:
    - name: mongo:latest
  script:
    - pip install tox
    - pip install tox-pip-version
    - tox -e coverage
  tags:
    - docker
  artifacts:
    paths:
      - $coverage_path
  allow_failure: true


sonar:
  stage: Post Static Analysis
  dependencies:
    - pytest
  allow_failure: true
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [ "" ]
  script:
    - sonar-scanner -h
    - sonar-scanner -D sonar.projectKey=futureofwork_orbis_2_webservice_AX8sGwtTzgg17GV5qrGE
                    -D sonar.language=py
                    -D sonar.host.url=$SONAR_HOST 
                    -D sonar.login=$SONAR_KEY 
                    -D sonar.python.coverage.reportPaths=$coverage_path
                    -D sonar.sources='src/'
                    -D sonar.exclusions='src/frontend/**'
    
  tags:
    - docker
  when: manual


docker:
  stage: Docker Build
  image:
    name: docker:latest
  script:
    - CI_VERSION="${VERSION}.${CI_PIPELINE_ID}"
    - echo building image $DOCKER_IMAGE
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t $DOCKER_IMAGE .
    - docker tag $DOCKER_IMAGE $DOCKER_IMAGE:latest
    - docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$CI_VERSION
    - docker push $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$CI_VERSION
  tags:
  - mavendocker
  when: manual

fhgr-deploy-production-release:
  image: dtzar/helm-kubectl:latest
  stage: Kubernetes Deployment
  script:
    - echo "Deploy to prodction cluster"
    - APPLICATION_NAME_APP=${APPLICATION_NAME}-app
    - CI_VERSION="${VERSION}.${CI_PIPELINE_ID}"
    - helm upgrade --install $APPLICATION_NAME_APP
      --kubeconfig $KUBECONFIG 
      --set gitlab.env=review/${CI_ENVIRONMENT_SLUG}
      --set gitlab.app=$CI_PROJECT_PATH_SLUG 
      --set image.repository=$DOCKER_IMAGE:$CI_VERSION
      --namespace $KUBE_NAMESPACE_FHGR
      --set appVersion=$CI_COMMIT_SHA ./$HELM_CHART_NAME_FHGR/app/
    - kubectl rollout restart deployment $APPLICATION_NAME_APP-template
  environment:
    name: production
    url:  https://${APPLICATION_NAME_APP}.${URL_FHGR}/rest/status
    on_stop: fhgr-delete-production-release
    kubernetes:
      namespace: $KUBE_NAMESPACE_FHGR
  tags:
    - mavendocker
  when: manual

fhgr-delete-production-release:
  image: dtzar/helm-kubectl:latest
  stage: Kubernetes Deployment
  variables:
    GIT_STRATEGY: none
  script:
    - APPLICATION_NAME_APP=${APPLICATION_NAME}-app
    - echo "removing production deployment $APPLICATION_NAME_APP-template from cluster..."
    - helm --kubeconfig $KUBECONFIG delete $APPLICATION_NAME_APP
  environment:
    name: production
    action: stop
  only:
    - master
  tags:
    - docker
  when: manual

fhgr-deploy-production-release-db:
  image: dtzar/helm-kubectl:latest
  stage: Kubernetes Deployment
  script:
    - echo "Deploy db to prodction cluster"
    - APPLICATION_NAME_DB=${APPLICATION_NAME}-db
    - CI_VERSION="${VERSION}.${CI_PIPELINE_ID}"
    - helm upgrade --install $APPLICATION_NAME_DB
      --kubeconfig $KUBECONFIG 
      --set gitlab.env=review/${CI_ENVIRONMENT_SLUG}
      --set gitlab.app=$CI_PROJECT_PATH_SLUG 
      --namespace $KUBE_NAMESPACE_FHGR
      --set appVersion=$CI_COMMIT_SHA ./$HELM_CHART_NAME_FHGR/db/
    - kubectl rollout restart deployment $APPLICATION_NAME_DB-template
  environment:
    name: production
    url:  https://${APPLICATION_NAME_DB}.${URL_FHGR}/rest/status
    on_stop: fhgr-delete-production-release
    kubernetes:
      namespace: $KUBE_NAMESPACE_FHGR
  tags:
    - mavendocker
  when: manual

fhgr-delete-production-release-db:
  image: dtzar/helm-kubectl:latest
  stage: Kubernetes Deployment
  variables:
    GIT_STRATEGY: none
  script:
    - APPLICATION_NAME_DB=${APPLICATION_NAME}-db
    - echo "removing db production deployment $APPLICATION_NAME_DB-template from cluster..."
    - helm --kubeconfig $KUBECONFIG delete $APPLICATION_NAME_DB
  environment:
    name: production
    action: stop
  only:
    - master
  tags:
    - docker
  when: manual

