version: "3.9"
services:
  orbis2:
    image: orbis2:latest
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo
    network_mode: host

  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    network_mode: host
