version: "3.9"
services:
  orbis2:
    image: orbis2:latest
    env_file:
      - .env
    restart: always
    ports:
      - "63010:63010"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
