apiVersion: v1
kind: Service
metadata:
  name: {{ include "autodeployment.fullname" . }}
  labels:
    {{- include "autodeployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "autodeployment.selectorLabels" . | nindent 4 }}
